### ISSUE TITLE
Attendance App

### ISSUE THREAD

**Issue by ideabrian** [florinpop17/100Days100Projects#13]
A teacher needs to see all her students then click or tap on the pictures of who's in class today.
An event host needs to check people in as they arrive.
A busy entrepreneur needs to see who clicked an email ( API check-in )

etc.

Attendance is a visual app to see pictures or avatars or placeholders of people who are participating.

People could check-in by clicking an email, tapping a button (somewhere), replying to a tweeet hooked up to a monitoring app -- lots of ways to provide, at a glance, a view of who is and who is not participating.

**Comment by GeorgeWL** [comment]
How does one stop them from doing what our class used to do, logging in our friends that weren't there using private browser? 😛

**Comment by ideabrian** [comment]
Trust.
