### ISSUE TITLE
Pokemon App using the Pokemon API

### ISSUE THREAD

**Issue by jamesqquick** [florinpop17/100Days100Projects#5]
Example pokedex - https://codepen.io/jamesqquick/pen/PoYXYVG

**Comment by florinpop17** [comment]
This one looks niice! 😄

**Comment by florinpop17** [comment]
@jamesqquick check out my version here: https://codepen.io/FlorinPop17/pen/gOYZxyE

I focused more on implementing the design found on dribbble. And I also used a little bit of your code! 👍

**Comment by florinpop17** [comment]
Project completed. Closing!
