### ISSUE TITLE
Sketch Battle

### ISSUE THREAD

**Issue by GeorgeWL** [florinpop17/100Days100Projects#8]
Two Fighters Go in.

One goes out.

Draw a fighter using the canvas, the game secretly tools up some stats, then they fight.

**Comment by florinpop17** [comment]
Hmm.. maybe you might want to be a little more descriptive about this project 😅

**Comment by GeorgeWL** [comment]
haha, yeh I didn't put anywhere near enough thought in there.

It's taken from an old forum game, and was thinking it could possibly be adapted.

The forum game was as such: 
1. Each player submitted a terrible sketch made using MS Paint (or similarly limited art app) and stated which side of a Battlefield (Left/Right) they wanted to be on.
2. Then either through user votes (most commonly this), or the originator of the post assigning values, the two sides of a battlefield would "fight" and a winning side would be decided.

Was thinking this could be adapted into a 1v1 variant using the javascript canvas API.
